In [1]:
#multiple series together is known as dataframe 
import numpy as np 
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
#using list 

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [13]:
df2= pd.DataFrame(data_list)
col=["name" , "age" , "city","salary"] # manually have to set data 
df2 = pd.DataFrame(data_list , columns = col)

In [14]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
#Selection and indexing of column 
df2[["name" ,"city"]] # we need to provide list of list for multiple column

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [20]:
df2["name"]

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [21]:
#Creating a new column 
df2["Designation"] = ["doc" , "eng" , "arc" , "eng"]

In [22]:
df2

    name  age      city  salary Designation
0   John   28  New York   65000         doc
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000         arc
3  Linda   42    London   85000         eng

In [24]:
#remove a column 
# df2.drop("Designation")#it wont work as bydefault axis is zero 
df2.drop('Designation' , axis=1)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2
#disgnation is not deleted ?!

    name  age      city  salary Designation
0   John   28  New York   65000         doc
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000         arc
3  Linda   42    London   85000         eng

In [26]:
df2.drop('Designation' , axis=1  , inplace=True)#this will delete the column permanently

In [27]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df2.drop(["city" , "salary"] , axis=1) #for multiple column at once

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [31]:
#for row 
df2.drop(1 , axis=0)

    name  age      city  salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [32]:
#selecting Rows 
df2.loc[0] #loc means location use for rows

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [33]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
#multiple rows

In [39]:
df2.loc[[1,2]]

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [40]:
#index location
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [44]:
# particular portion 
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [47]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [50]:
df.loc[[2,3]][["Name" , "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [51]:
#conditional selection 
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [52]:
#age>30 only 
df2[df2["age"]>30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [57]:
#Age>30 and city =paris
df2[(df2["age"]>30 )& (df2["city"]=="Paris") ]

   name  age   city  salary
1  Anna   34  Paris   70000