In [5]:
import numpy as np 
import pandas as pd

In [7]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df= pd.DataFrame(data)

In [8]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [12]:
df.isna().sum() #kitni null values hai ?

A    1
B    0
C    2
D    3
dtype: int64

In [14]:
df.isna().any() # any column with no null value ?

A     True
B    False
C     True
D     True
dtype: bool

In [18]:
#use of threshold 
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.dropna(thresh=3) #vo rows jisme 3 atleast non null values ho

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [21]:
#filling the missign data 
df.fillna(888888) #fill nan with 8888888

          A  B         C         D
0       1.0  1       1.0       1.0
1       2.0  2       2.0  888888.0
2  888888.0  3       3.0  888888.0
3       4.0  4  888888.0  888888.0
4       5.0  5  888888.0       5.0

In [25]:
#fill by column 
val={"A":111, "B":222,"C":333,"D":444} #to actually change the original value just put the inplace 
df.fillna(value=val)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  444.0
2  111.0  3    3.0  444.0
3    4.0  4  333.0  444.0
4    5.0  5  333.0    5.0

In [27]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0